In [3]:
#imports
import pandas as pd 
import numpy as np

In [5]:
# load data
df = pd.read_excel("../data/Base_coronavirus_31-05-2021.xlsx")
df.head()

,id,ano,semana,fecha_not,diresa,red,microred,establecimiento,institucion,clasificacion,...,prueba_rap,resultado_rap,fecha_res_rap,fecha_rap1,muestra_rap1,prueba_rap1,resultado_rap1,fecha_res_rap1,secuenciamiento,asintomatico
0,542,2021,5,09-02-2021,PUNO,PUNO,SIN MICRORED,"HOSP. REG. ""MANUEL NUÑEZ BUTRÓN"" - PUNO",GOBIERNO REGIONAL,DESCARTADO,...,NaN,NaN,NaN,00-00-0000,NaN,NaN,NaN,NaN,NaN,NaN
1,1234,2020,10,07-03-2020,PUNO,SAN ROMAN,SIN MICRORED,"HOSP. ""CARLOS MONGE MEDRANO"" - JULIACA",GOBIERNO REGIONAL,DESCARTADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1258,2020,10,09-03-2020,PUNO,PUNO,SIN MICRORED,HOSPITAL III DE ESSALUD,ESSALUD,DESCARTADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1266,2020,10,09-03-2020,PUNO,SAN ROMAN,SIN MICRORED,"HOSP. ""CARLOS MONGE MEDRANO"" - JULIACA",GOBIERNO REGIONAL,DESCARTADO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1292,2021,9,05-03-2021,PUNO,PUNO,METROPOLITANO,C.S. METROPOLITANO PUNO,GOBIERNO REGIONAL,CONFIRMADO,...,SEROLOGIA,NEGATIVO,16-07-2020,00-00-0000,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.shape

(95315, 179)

In [7]:
duplicados = df[df.duplicated(keep=False)] #obtenemos los duplicados

duplicados = duplicados.sort_values(by=df.columns.tolist()) #ordena los duplicados

duplicados.head(10) #muestra los primeros duplicados

Empty DataFrame
Columns: [id, ano, semana, fecha_not, diresa, red, microred, establecimiento, institucion, clasificacion, punto, fecha_det, entrada, edad, tipo_edad, sexo, peso, talla, nacionalidad, pais_nacionalidad, migrante, pais_origen, pais_residencia, departamento_residencia, provincia_residencia, residencia, ubigeo, etnia, fecha_ini, departamento_infeccion, provincia_infeccion, distrito_infeccion, ubigeo_infeccion, hospitalizado, fecha_hos, eess, seguro, diagnostico_ing, aislamiento, fecha_ais, convulsion_hos, disnea_hos, coma_hos, auscultacion_hos, radiografia_hos, ecografia_hos, tomografia_hos, rmn_hos, otro_hos, servicio, servicio_otro, ventilacion, entubado, neumonia, evolucion, fecha_alt, fecha_def, hora_def, lugar_def, fiebre, malestar, tos, garganta, congestion, respiratoria, diarrea, nauseas, cefalea, irritabilidad, muscular, abdominal, pecho, articulaciones, anosmia, ageusia, oido, otros_sintomas, temperatura, exudado, conjuntival, convulsion, coma, disnea, auscultacion, rxpulmonar, ecografia, tomografia, rmn, otros_signos, embarazo, trimestre, postparto, cardiovascular, diabetes, hepatica, neurologica, inmunodeficiencia, renal, hepatico, pulmonar, ...]
Index: []

[0 rows x 179 columns]

In [8]:
print(df.duplicated().sum())

0

In [9]:
# tipos de datos Numericas (Continuas, discretas)
# ["id","edad","peso","talla","ubigeo","infeccion","temperatura","ubigeo_trabajo"]
df_continuas = df[["edad","peso","talla","temperatura"]]
df_discretas = df[["id","ubigeo","ubigeo_trabajo","ano","semana"]]

print(f"Variables continuas:")
df_continuas.info(verbose=True, show_counts=True)
print(f"Variables discretas:")
df_discretas.info(verbose=True, show_counts=True)

Variables continuas:
<class 'pandas.DataFrame'>
RangeIndex: 95315 entries, 0 to 95314
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   edad         95315 non-null  int64
 1   peso         37097 non-null  float64
 2   talla        37097 non-null  float64
 3   temperatura  66668 non-null  float64
dtypes: float64(3), int64(1)
memory usage: 2.9 MB
Variables discretas:
<class 'pandas.DataFrame'>
RangeIndex: 95315 entries, 0 to 95314
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              95315 non-null  int64
 1   ubigeo          95298 non-null  object
 2   ubigeo_trabajo  3686 non-null   object
 3   ano             95315 non-null  int64
 4   semana          95315 non-null  int64
dtypes: int64(3), object(2)
memory usage: 3.6+ MB

In [10]:
# categoricas (nominales, ordinales)

df_nominales = df[["diresa","red","microred","establecimiento","institucion","entrada","sexo","nacionalidad","pais_nacionalidad","migrante","pais_origen","pais_residencia","departamento_residencia","provincia_residencia","residencia","etnia","departamento_infeccion","provincia_infeccion","distrito_infeccion","hospitalizado","eess","seguro","diagnostico_ing","aislamiento","convulsion_hos","disnea_hos","coma_hos","auscultacion_hos","radiografia_hos","ecografia_hos","tomografia_hos","rmn_hos","otro_hos","servicio_otro","ventilacion","entubado","neumonia","hora_def","lugar_def","fiebre","malestar","tos","garganta","congestion","respiratoria","diarrea","nauseas","cefalea","irritabilidad","muscular","abdominal","pecho","articulaciones","anosmia","ageusia","oido","otros_sintomas","exudado","conjuntival","convulsion","coma","disnea","auscultacion","rxpulmonar","ecografia","tomografia","rmn","otros_signos","embarazo","trimestre","postparto","cardiovascular","diabetes","hepatica","neurologica","inmunodeficiencia","renal","hepatico","pulmonar","cancer","obesidad","tbc","asma","otros_comorbilidad","ocupacion","otra_ocupacion","profesion","diresa_trabajo","red_trabajo","microred_trabajo","eess_trabajo","departamento_trabajo","provincia_trabajo","distrito_trabajo","viajado_14","pais_1","ciudad_1","pais_2","ciudad_2","pais_3","ciudad_3","eess_14","esalud_14","contacto_14","contacto_salud","contacto_familiar","contacto_trabajo","contacto_desconocido","contacto_otro","confirmado_14","entorno_salud","entorno_familiar","entorno_trabajo","casa_reposo","centro_penitenciario","albergue","entorno_desconocido","entorno_otro","contacto_pais","departamento_contacto","provincia_contacto","contacto_ubigeo","contacto_localidad","mercado","mercado_pais","departamento_mercado","provincia_mercado","contacto_mercado","mercado_localidad","muestra","prueba","resultado","muestra1","prueba1","resultado1","muestra2","prueba2","resultado2","muestra_rap","prueba_rap","resultado_rap","muestra_rap1","prueba_rap1","resultado_rap1","fecha_res_rap1","secuenciamiento","asintomatico"]]
df_ordinales = df[["clasificacion","servicio","evolucion"]]

print(f"Variables categoricas nominales:")
df_nominales.info(verbose=True, show_counts=True)
print(f"Variables categoricas ordinales:")
df_ordinales.info(verbose=True, show_counts=True)

Variables categoricas nominales:
<class 'pandas.DataFrame'>
RangeIndex: 95315 entries, 0 to 95314
Data columns (total 147 columns):
 #    Column                   Non-Null Count  Dtype
---   ------                   --------------  -----
 0    diresa                   95315 non-null  str
 1    red                      95315 non-null  str
 2    microred                 95218 non-null  str
 3    establecimiento          95298 non-null  str
 4    institucion              95298 non-null  str
 5    entrada                  340 non-null    str
 6    sexo                     95315 non-null  str
 7    nacionalidad             23659 non-null  str
 8    pais_nacionalidad        37097 non-null  str
 9    migrante                 13429 non-null  str
 10   pais_origen              37097 non-null  str
 11   pais_residencia          95315 non-null  str
 12   departamento_residencia  95294 non-null  str
 13   provincia_residencia     95294 non-null  str
 14   residencia               95294 non-null  str
 15   etnia                    79757 non-null  str
 16   departamento_infeccion   18252 non-null  str
 17   provincia_infeccion      18252 non-null  str
 18   distrito_infeccion       18252 non-null  str
 19   hospitalizado            95315 non-null  str
 20   eess                     5955 non-null   str
 21   seguro                   3817 non-null   str
 22   diagnostico_ing          2726 non-null   str
 23   aislamiento              66668 non-null  str
 24   convulsion_hos           32403 non-null  float64
 25   disnea_hos               32441 non-null  float64
 26   coma_hos                 32404 non-null  float64
 27   auscultacion_hos         32452 non-null  float64
 28   radiografia_hos          32438 non-null  float64
 29   ecografia_hos            32403 non-null  float64
 30   tomografia_hos           32407 non-null  float64
 31   rmn_hos                  32404 non-null  float64
 32   otro_hos                 0 non-null      float64
 33   servicio_otro            682 non-null    str
 34   ventilacion              33517 non-null  str
 35   entubado                 6477 non-null   str
 36   neumonia                 6374 non-null   str
 37   hora_def                 37097 non-null  float64
 38   lugar_def                2353 non-null   str
 39   fiebre                   95315 non-null  int64
 40   malestar                 95315 non-null  int64
 41   tos                      95315 non-null  int64
 42   garganta                 95315 non-null  int64
 43   congestion               95315 non-null  int64
 44   respiratoria             95315 non-null  int64
 45   diarrea                  95315 non-null  int64
 46   nauseas                  95315 non-null  int64
 47   cefalea                  95315 non-null  int64
 48   irritabilidad            95315 non-null  int64
 49   muscular                 95315 non-null  int64
 50   abdominal                95315 non-null  int64
 51   pecho                    95315 non-null  int64
 52   articulaciones           95315 non-null  int64
 53   anosmia                  37097 non-null  float64
 54   ageusia                  37097 non-null  float64
 55   oido                     37097 non-null  float64
 56   otros_sintomas           5475 non-null   object
 57   exudado                  95315 non-null  int64
 58   conjuntival              95315 non-null  int64
 59   convulsion               95315 non-null  int64
 60   coma                     66668 non-null  float64
 61   disnea                   95315 non-null  int64
 62   auscultacion             95315 non-null  int64
 63   rxpulmonar               95315 non-null  int64
 64   ecografia                37097 non-null  float64
 65   tomografia               37097 non-null  float64
 66   rmn                      37097 non-null  float64
 67   otros_signos             11214 non-null  object
 68   embarazo                 95315 non-null  int64
 69   trimestre                95315 non-null  int64
 70   postparto                95315 non-null  int64
 71   cardiovascular           95315 non-null  int64
 72   diabetes                 95315 non-null  int64
 73   hepatica                 95315 non-null  int64
 74   neurologica              95315 non-null  int64
 75   inmunodeficiencia        95315 non-null  int64
 76   renal                    95315 non-null  int64
 77   hepatico                 66668 non-null  float64
 78   pulmonar                 95315 non-null  int64
 79   cancer                   95315 non-null  int64
 80   obesidad                 37097 non-null  float64
 81   tbc                      37097 non-null  float64
 82   asma                     37097 non-null  float64
 83   otros_comorbilidad       14200 non-null  object
 84   ocupacion                95315 non-null  str
 85   otra_ocupacion           63701 non-null  object
 86   profesion                1846 non-null   str
 87   diresa_trabajo           2412 non-null   str
 88   red_trabajo              2390 non-null   str
 89   microred_trabajo         2030 non-null   str
 90   eess_trabajo             1999 non-null   str
 91   departamento_trabajo     3356 non-null   str
 92   provincia_trabajo        3356 non-null   str
 93   distrito_trabajo         3356 non-null   str
 94   viajado_14               66668 non-null  str
 95   pais_1                   66668 non-null  str
 96   ciudad_1                 7118 non-null   object
 97   pais_2                   66668 non-null  str
 98   ciudad_2                 857 non-null    str
 99   pais_3                   66668 non-null  str
 100  ciudad_3                 146 non-null    str
 101  eess_14                  66668 non-null  str
 102  esalud_14                3854 non-null   str
 103  contacto_14              66668 non-null  str
 104  contacto_salud           66668 non-null  float64
 105  contacto_familiar        66668 non-null  float64
 106  contacto_trabajo         66668 non-null  float64
 107  contacto_desconocido     66668 non-null  float64
 108  contacto_otro            363 non-null    str
 109  confirmado_14            95315 non-null  str
 110  entorno_salud            95315 non-null  int64
 111  entorno_familiar         95315 non-null  int64
 112  entorno_trabajo          95315 non-null  int64
 113  casa_reposo              37097 non-null  float64
 114  centro_penitenciario     37097 non-null  float64
 115  albergue                 37097 non-null  float64
 116  entorno_desconocido      95315 non-null  int64
 117  entorno_otro             887 non-null    object
 118  contacto_pais            66668 non-null  str
 119  departamento_contacto    7230 non-null   str
 120  provincia_contacto       7230 non-null   str
 121  contacto_ubigeo          7230 non-null   str
 122  contacto_localidad       6867 non-null   str
 123  mercado                  61719 non-null  str
 124  mercado_pais             66668 non-null  str
 125  departamento_mercado     2004 non-null   str
 126  provincia_mercado        2004 non-null   str
 127  contacto_mercado         2004 non-null   str
 128  mercado_localidad        1940 non-null   str
 129  muestra                  38265 non-null  str
 130  prueba                   37606 non-null  str
 131  resultado                36840 non-null  str
 132  muestra1                 4163 non-null   str
 133  prueba1                  4138 non-null   str
 134  resultado1               4057 non-null   str
 135  muestra2                 797 non-null    str
 136  prueba2                  797 non-null    str
 137  resultado2               771 non-null    str
 138  muestra_rap              62698 non-null  str
 139  prueba_rap               61121 non-null  str
 140  resultado_rap            62727 non-null  str
 141  muestra_rap1             7251 non-null   str
 142  prueba_rap1              7102 non-null   object
 143  resultado_rap1           7248 non-null   str
 144  fecha_res_rap1           7234 non-null   str
 145  secuenciamiento          0 non-null      float64
 146  asintomatico             38970 non-null  str
dtypes: float64(29), int64(35), object(7), str(76)
memory usage: 106.9+ MB
Variables categoricas ordinales:
<class 'pandas.DataFrame'>
RangeIndex: 95315 entries, 0 to 95314
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   clasificacion  95311 non-null  str
 1   servicio       2588 non-null   str
 2   evolucion      27838 non-null  str
dtypes: str(3)
memory usage: 2.2 MB

In [11]:
# temporales (Series de tiempo, Duraciones)
df_temp_series = df[["fecha_not","fecha_det","fecha_ini","fecha_res_rap1","fecha_rap1","fecha_res_rap","fecha_rap","fecha_res2","fecha_mue2","fecha_res1","fecha_mue1","fecha_res","fecha_mue","culmina_embarazo","fecha_def","fecha_alt","fecha_ais","fecha_hos","fecha_ini","fecha_det","fecha_not"]]

print(f"Variables temporales (series de tiempo):")
df_temp_series.info(verbose=True, show_counts=True)

Variables temporales (series de tiempo):
<class 'pandas.DataFrame'>
RangeIndex: 95315 entries, 0 to 95314
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fecha_not         95315 non-null  str
 1   fecha_det         66668 non-null  str
 2   fecha_ini         95315 non-null  str
 3   fecha_res_rap1    7234 non-null   str
 4   fecha_rap1        66656 non-null  str
 5   fecha_res_rap     62222 non-null  str
 6   fecha_rap         66657 non-null  str
 7   fecha_res2        37097 non-null  str
 8   fecha_mue2        37097 non-null  str
 9   fecha_res1        95305 non-null  str
 10  fecha_mue1        95305 non-null  str
 11  fecha_res         95315 non-null  str
 12  fecha_mue         95315 non-null  str
 13  culmina_embarazo  37097 non-null  str
 14  fecha_def         95315 non-null  str
 15  fecha_alt         37097 non-null  str
 16  fecha_ais         95315 non-null  str
 17  fecha_hos         95315 non-null  str
 18  fecha_ini         95315 non-null  str
 19  fecha_det         66668 non-null  str
 20  fecha_not         95315 non-null  str
dtypes: str(21)
memory usage: 15.3 MB